# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-18 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_reg_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('genre', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guests', models.ManyToManyField(related_name='guest', to='login_reg_app.Users')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='login_reg_app.Users')),
            ],
        ),
    ]
